imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [!event]
        console:
            type:   console
            bubble: false
            channels: [!event, !doctrine]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

#swiftmailer:
#    delivery_address: me@example.com

bazinga_faker:
    orm: doctrine
    locale: fr_FR
    entities:
        AppBundle\Entity\Place:
            number: 10
            custom_formatters:
                name: { method: company }
                description: { method: realText }
                city: { method: city }
                street: { method: streetAddress }
                zip_code: { method: postcode }
                country: { method: country }
                latitude: { method: latitude, parameters: [ 44.7, 44.9 ]}
                longitude: { method: longitude, parameters: [ -0.6, -0.48 ]}
                phone: { method: phoneNumber }
                mobile: { method: mobileNumber }
                email: { method: safeEmail }
                website: { method: url }
                facebook: { method: url }
        AppBundle\Entity\Meal:
            number: 100
            custom_formatters:
                name: { method: company }
<<<<<<< HEAD
=======

ivory_google_map:
    map:
        debug: "%kernel.debug%"
        language: "%locale%"
>>>>>>> a4799e24bc0d5c32fff3ae1bf471faa798d473dc
